### ISSUE TITLE
输入法注册到系统之后没办法去掉

### ISSUE THREAD

**Issue by ran-err** [copyliu/YIME#5]
如图，会一直停留在系统里，即使程序关闭了也没办法删除
![图片](https://user-images.githubusercontent.com/42885699/113713691-35a6cd80-971a-11eb-8d75-9fbcfbed6b41.png)

**Comment by copyliu** [comment]
https://github.com/copyliu/YIME/blob/master/YIME/Program.cs#L32 
見反註冊方式
