### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by aiduhuihuang** [copyliu/YIME#6]
您好，我用了你的pinyin分支,但是总是加载的时候报错，我用的似乎win10的环境,x64的。希望能够指导下，感谢。我的qq:972022747

**Comment by copyliu** [comment]
此项目从未完工, 主分支只实现了安装注册输入法到系统, 以及外置调用RIME后端的测试工具而已.
新的pinyin分支甚至只用来做前期研究.

**Comment by aiduhuihuang** [comment]
很感谢你的回答，谢谢。你说的主分支调用了RIME后端,是否有办法测试上屏，大神。

**Comment by aiduhuihuang** [comment]
pinyin_new分支，我家在了pinyin.dll总是报错.以为是我dll下载错了，试了很多，没效果

**Comment by copyliu** [comment]
不能 只实现到注册进系统而已
另外的playground算是调用RIME后端的尝试.

**Comment by aiduhuihuang** [comment]
Session ID: 18456392
w
I1102 10:23:16.228113 18560 rime_api.cc:726] simulate key sequence: w
Commit:
Status: False,False, .default
Context: ,
w
I1102 10:23:17.633196 18560 rime_api.cc:726] simulate key sequence: w
Commit:
Status: False,False, .default
Context: ,
屏幕上都是这个，怎么激活RIME呢？感谢感谢。我想调试看效果，在一次谢谢您的回复，是否有教程

**Comment by copyliu** [comment]
其实已经成功调用了RIME了, 但是RIME本体初次运行的时候需要一段时间进行初始化和生成词典, 这一个过程是RIME自身完成的, 初始化完成之前不会有候选字返回, 你可以维持playground运行一阵子留意CPU是否占用下降.

这个项目因为拖延症拖了太久了 很多细节都有点遗忘.

**Comment by aiduhuihuang** [comment]
理解理解。我也是最近公司需要搞输入法，头大得很。完全没有头绪 @

**Comment by copyliu** [comment]
主分支大体上注册是成功了 输入也能有事件抓到, 只不过当年RIME的api实在不友好, 而且调试其实非常麻烦, 就暂时放置了,
libpinyin的API更友好但是在windows上的编译使用都非常棘手

libpinyin的分支我记得是编译成功而且能调用一部分API但是很多*nix编译到windows的常见问题需要解决(比如路径带中文之类)

**Comment by aiduhuihuang** [comment]
我就是想用libpinyin,但是一直报错，报加载pinyin.dll有问题。所以不知道怎么弄，就想到请教您得。Rime我看了设置也太多

**Comment by aiduhuihuang** [comment]
using var context = new PinyinContext("data", "用户配置");
using var input = context.CreateNewInput();
input.SetInput("rufahaimeizuowan", "输");
在pinyincontext中的
LibPinyinDll.pinyin_init(datadir, userdir);
报错了

**Comment by copyliu** [comment]
datadir和userdir要英文, 中文目录应该是有问题

**Comment by aiduhuihuang** [comment]
显示的是无法加载pinyin.dll这个问题。我开始换成了英文的。感谢感谢
[DllImport("Pinyin.dll", CallingConvention = CallingConvention.Cdecl)]

BadImageFormatException: 试图加载格式不正确的程序

**Comment by copyliu** [comment]
你可能需要编译成x64的, 然后项目本身也要编译成x64

**Comment by copyliu** [comment]
另外还得搞一套词库数据下来光有DLL是不行的, 这个你可以从各大linux发行版抓, 然后丢进datadir指定的目录

我记得这个在编译dll的时候会一并生成但是生成脚本无法在windows运行, 最后我还得找个wsl手动做

**Comment by aiduhuihuang** [comment]
希望指导下，是否方便联系，请教下，我下载几个dll，都试过了，就是报错。哎。。。。。。。。感谢感谢.
vx:     diser9988
真心请教学习

**Comment by aiduhuihuang** [comment]
如果你方便的话哈，联系下。感谢感谢
